# Generated by Django 4.0.4 on 2022-05-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_chead2_alter_blogpost_head2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='chead2',
            new_name='conthead2',
        ),
    ]
