# Generated by Django 4.0.4 on 2022-05-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
